name: Test

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.7.1

      - name: Test
        run: go test -race ./...
